name: Build runner's image

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/docker-runner-images.yml"
      - "runners/**"

jobs:
  changes:
    name: Get changes
    runs-on: ubuntu-24.04
    outputs:
      changed: ${{ steps.changed-files.outputs.all_modified_files }}
      name: ${{ steps.name.outputs.group1 }}
    steps:
      - name: Checkout sources        
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        id: changed-files
        with:
          files: runners/**
          dir_names: true
          dir_names_max_depth: '2'
          matrix: true

  build:
    name: Build runners' images
    needs:
      - changes
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: 
        dirs: ${{ fromJson(needs.changes.outputs.changed) }}
    steps:
      - name: Get env name
        uses: actions-ecosystem/action-regex-match@d50fd2e7a37d0e617aea3d7ada663bd56862b9cc
        id: name
        with:
          text: ${{ matrix.dirs }}
          regex: '^.+\/(.+)'

      - run: |
          echo ${{ matrix.dirs }}
          echo ${{ steps.name.outputs.match }}
          echo ${{ steps.name.outputs.group1 }}
