name: Build runner's image

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/docker-runner-images.yml"
      - "runners/**"

jobs:
  changes:
    name: Get changes
    runs-on: ubuntu-24.04
    outputs:
      changed: ${{ steps.changed-files.outputs.all_modified_files }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        id: changed-files
        with:
          files: runners/**
          dir_names: true
          dir_names_max_depth: '2'
          json: true

      - run: |
          echo ${{ steps.changed-files.outputs.all_modified_files }}
          echo ${{ steps.changed-files.outputs.all_modified_files_count }}

  build:
    name: Build runners' images
    needs:
      - changes
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: 
        dirs: ${{ toJson(needs.changes.outputs.changed) }}
    steps:
      - run: |
          echo ${{ matrix.dirs }}
